# Generated by Django 5.1.4 on 2024-12-22 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_flower_del", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="notes",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(default="Not provided", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="000-000-0000", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
